levelfour/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

#TEMPLATE TAGGING
app_name =  'basic_app'

urlpatterns = [
    url('relative/', views.relative, name='relative'),
    url('other/', views.other, name='other'),
]

levelfour/levelfour/urls.py
from django.contrib import admin
from django.urls import include, path
from basic_app import views
# from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')),
]

levelfour/basic_app/models.py
from django.db import models

# Create your models here.

levelfour/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world!','number':100}
    return render(request,'basic_app/index.html', context_dict)


def other(request):
    return render(request,'basic_app/other.html')


def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

levelfour/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- BOOTSTRAP CDN LINK TO CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:other'%}">OTHER</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      <!-- ANYTHING OUTSIDE THIS WILL BE INHERITED IF YOU EXTEND -->
      {% endblock %}
    </div>
  </body>
</html>

levelfour/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>INDEX</h1>
    <h2>This INDEX page through TEMPLATE INHERITANCE!</h2>
    <h1>{{ text | cut:'hello' }}</h1>
    <h1>{{ text | cut:'world' }}</h1>
    <h1>{{ number | add:'20' }}</h1>
  {% endblock %}

levelfour/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>OTHER</h1>
    <h2>This is an example of TEMPLATE INHERITANCE!</h2>
  {% endblock %}

levelfour/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
    <br>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
    <br>
    <a href="{% url 'index' %}">INDEX</a>
  </body>
</html>